version: '3'
services:
  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - '${MYSQL_PORT}:3306'
  atrocore:
    build: .
    volumes:
      # - './apache/sites-available/localhost.conf:/etc/apache2/sites-available/localhost.conf'
      - './php/apache2/php.ini:/etc/php/7.4/apache2/php.ini'
    depends_on:
      - mysql
    ports:
      - '${APP_PORT}:80'
    command: >
      bash -c "
        a2enmod rewrite &&
        apache2-foreground
      "
    # volumes: 
    #   - astrocore:/var/www/astrocore
